name:                weibo-export
version:             0.1.0.0
github:              "easoncxz/weibo-export"
license:             BSD3
author:              "Eason Chen"
maintainer:          "easoncxz@gmail.com"
copyright:           "2020 easoncxz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/easoncxz/weibo-export#README.md>

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DuplicateRecordFields
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoMonomorphismRestriction
- OverloadedStrings
- OverloadedLabels
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators

# Hideous big lump of dependencies all piled into one pile
# because ghcide cannot handle multiple Cabal components.
dependencies:
    # --- library:
  - aeson
  - aeson-pretty
  - base >= 4.7 && < 5
  - bytestring
  - case-insensitive
  - containers
  - directory
  - filepath
  - generic-lens
  - http-client
  - http-client-tls
  - http-types
  - lens
  - lens-aeson
  - mtl
  - optparse-applicative
  - pretty-simple
# - servant
# - servant-client
# - servant-client-core
  - text
  - tostring
  - turtle
  - utf8-string
  - vector
  - wreq
    # --- exe:
  - Cabal
  - base
  - text
    # --- tests:
  - HUnit
  - aeson
  - base
  - bytestring
  - directory
  - filepath
  - hspec
  - lens
  - mtl

library:
  source-dirs: src
  other-modules:
    Paths_weibo_export
  ghc-options:
  - -Wall


executables:
  weibo-export:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
      - weibo-export

tests:
  t:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - weibo-export
