name:                weibo-export
version:             0.1.0.0
github:              "githubuser/weibo-export"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/weibo-export#readme>

default-extensions:
- DataKinds
- DeriveGeneric
- EmptyDataDecls
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - http-client
  - http-client-tls
  - http-types
  - lens
  - pretty-simple
  - servant
  - servant-client
  - text
  - turtle
  - utf8-string
  - vector
  - wreq


executables:
  weibo-export-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - weibo-export

tests:
  weibo-export-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - weibo-export
    - hspec
    - aeson
    - bytestring
    - directory
    - filepath
    - HUnit
