name:                weibo-export
version:             0.1.0.0
github:              "githubuser/weibo-export"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/weibo-export#readme>

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DisambiguateRecordFields
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- TypeOperators

# Hideous big lump of dependencies all piled into one pile
# because ghcide cannot handle multiple Cabal components.
dependencies:
    # --- library:
  - aeson
  - aeson-pretty
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - directory
  - filepath
  - http-client
  - http-client-tls
  - http-types
  - lens
  - mtl
  - pretty-simple
  - servant
  - servant-client
  - servant-client-core
  - text
  - tostring
  - turtle
  - utf8-string
  - vector
  - wreq
    # --- exe:
  - Cabal
  - base
  - text
    # --- tests:
  - HUnit
  - aeson
  - base
  - bytestring
  - directory
  - filepath
  - hspec
  - lens
  - mtl

library:
  source-dirs: src
  ghc-options:
  - -Wall


executables:
  weibo-export-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
      - weibo-export

tests:
  weibo-export-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - weibo-export
