# This is a basic workflow to help you get started with Actions

name: Test and deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  create:
    # Branch or tag created

env:
  EASONCXZ_GITHUB_OAUTH_TOKEN_v2: "${{ secrets.EASONCXZ_GITHUB_OAUTH_TOKEN_v2 }}"
  EASONCXZ_BINTRAY_API_KEY: "${{ secrets.EASONCXZ_BINTRAY_API_KEY }}"


jobs:
  test:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Look at github context variable
      run: |
        echo 'event.ref: ${{ github.event.ref }}'
        echo 'event.head: ${{ github.event.head }}'
        echo 'event_path: ${{ github.event_path }}'
        echo 'event_name: ${{ github.event_name }}'
        echo 'ref: ${{ github.ref }}'
        cat "${{ github.event_path }}"

    - name: 'Look at the `create` event'
      if: github.event_name == 'create'
      run: |
        echo 'ref_type: ${{ github.event.ref_type }}'
        echo 'ref: ${{ github.event.ref }}'

    - name: 'Cache ~/.stack'
      id: cache-hs-stack
      uses: 'actions/cache@v1'
      with:
        path: ~/.stack
        key: "${{ runner.os }}-stack"

    - name: 'Cache .stack-work'
      id: cache-hs-stack-work
      uses: 'actions/cache@v1'
      with:
        path: .stack-work
        key: "${{ runner.os }}-stack-work"

    - name: Install Stack and Haskell dependencies
      run: ./automation/install-stack.sh

    - name: Compile and test
      run: stack --no-terminal test

  deploy:
    runs-on: macos-10.15
    needs: test
    if: github.event_name == 'create' && github.event.ref_type == 'tag'

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install homebrew_automation
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: ./automation/install-homebrew-automation.sh


    - name: Bottle and upload
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: ./automation/bottle-and-upload.sh

    - name: Gather and publish
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: ./automation/gather-and-publish.sh
